version: '2.1'

services:
  as:
    build: as
    container_name: as
    ports:
      - 8081:8080
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rs:
    build: rs
    container_name: rs
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  client:
    build: client
    container_name: client
    ports:
      - 8082:8080
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker


